### PR TITLE
Add ability to train on Habana Gaudi

### PR DESCRIPTION
**Pull request by jmduarte**
For discussion/testing... to see what parts we can integrate

### CODE REVIEW

**Comment by jmduarte** [comment]
@erwulff can you try out my yaml (modifying dataset locations, etc.) yourself to check if it works?

**Comment by erwulff** [comment]
> @erwulff can you try out my yaml (modifying dataset locations, etc.) yourself to check if it works?

@jmduarte Sure! I just tried it out and it didn't work using version 1.2 of the dataset (which is the only version I had on voyager). That's probably due to some compatibility issue between tf/tfds versions that were used in v1.2 and what you have in your container image (which I used for my tests). So I copied your mini version of v1.4.0 and tried using that. Seems to work fine, tested running 10 epochs without crashes and the loss is decreasing. Nice job!

**Comment by jpata** [comment]
The code changes look quite benign so I think this could go in as-is. Maybe the only question is to confirm that multi-GPU training still works after having moved the model.fit inside the strategy scope (unsure why it was outside of it before).

**Comment by jmduarte** [comment]
@jpata I think this is ready to be merged!

**Comment by jpata** [comment]
Awesome, thanks!

**Pull request merged**
