### PR TITLE
added qcd and ttbar labels to plots

### PR DESCRIPTION
**Pull request by jpata**
Add QCD and ttbar plot labels.

### CODE REVIEW

**Comment by jpata** [comment]
The new plots look like this, comments welcome @jmduarte.
num_particles

**Comment by jpata** [comment]
I guess this is better:
alt text

**Comment by jmduarte** [comment]
Looks good, but it might be better switch the text to "QCD, 14 TeV, 200 PU" for consistency (since it's all simulation anyway) and put it inside the canvas whenever possible. 

From a quick look, 
- it should be possible to make it a legend title for Fig. 2
- put it in the bottom right corner for Fig. 4 
- for Fig. 5 it can probably be on the same line as the other label like "MLPF, QCD, 14 TeV, 200 PU", 
- for Fig. 6, 7, and 8 it can be a two-line legend title (maybe)
- for Fig. 10, for consistency, we can change the label to "ttbar, 14 TeV"

**Comment by jmduarte** [comment]
Looks good to me!

**Comment by jpata** [comment]
thanks, I opted to put the sample string always in the legend.

**Pull request merged**
