### PR TITLE
GNN training

### PR DESCRIPTION
**Pull request by jmduarte**
First attempt; not quite working yet. Things to fix:

- [x] Get it actually training
- [x] Set realistic truth (currently set to connect edges `dR<0.2`)
- [ ] Currently training on 1 graph of clusters -> use 3 graphs of (cluster, cluster), (track, track), (cluster, track) pairs
- [x] Use singularity? (need to get a singularity image with `pytorch_geometric`)

### CODE REVIEW

**Comment by jpata** [comment]
Nice!

I just added the ground truth based on PFAlgo, see #1 for a discussion and the [data.ipynb](../blob/4706dbf485ddee9d857b78613d87ca25dabc66c4/notebooks/data.ipynb) notebook on how to use it.

```bash
$ root -l ./data/testing/step3_AOD_ntuple.root
root [3] linktree_elemtocand->Scan("linkdata_elemtocand_iblock:linkdata_elemtocand_ielem:linkdata_elemtocand_icand")
***********************************************************
*    Row   * Instance * linkdata_ * linkdata_ * linkdata_ *
***********************************************************
*        0 *        0 *         0 *         0 *      1836 *
*        0 *        1 *         1 *        19 *       381 *
*        0 *        2 *         1 *        19 *       827 *
*        0 *        3 *         1 *        19 *       974 *
*        0 *        4 *         1 *        20 *      2125 *
*        0 *        5 *         1 *        21 *       814 *
*        0 *        6 *         1 *        22 *       449 *
```

Did the singularity /storage/group/gpu/software/singularity/edge.simg image work [1]? Otherwise, @vlimant can update the image.

The following files should be used at Caltech, I will need to run via CRAB again:
- full CMSSW output: `/storage/user/jpata/particleflow/data/testing/step3_AOD.root`
- ntuple: `/storage/user/jpata/particleflow/data/testing/step3_AOD_ntuple.root`

[1] https://github.com/cmscaltech/gpuservers#singularity

**Comment by lgray** [comment]
On checklist item 3 - do we really want three graphs? If we are already doing a track - cluster graph why not just make big graph with all connections?

**Comment by jmduarte** [comment]
Hi @lgray, I was thinking we want 3 separate graphs because the concatenated edge features would have different sizes (i.e. a track has p, eta, phi, charge and a cluster has energy, eta, phi at least currently) so we could use different NNs in the edge convolution step. 

However, you're right that we could consider everything in one big graph, as long as we "reshape" things so every node (whether cluster or track) has the same set of features. Essentially, we could also "zero-out"  the ones that aren't there for clusters, etc.

**Comment by jpata** [comment]
@jmduarte as discussed offline, for the training of the clustering, you or your students could give a try with the outputs produced using `test/graph.py`, stored in
`/storage/user/jpata/particleflow/data/TTbar/191007_162300/step3_AOD_*.npz`

Each file contains the following arrays for one event:
- `elements: (nelem, nfeat_elem)`, all the PF elements, [type, energy, eta, phi, ...]
- `element_block_id: (nelem)`, unique ID for each element based on the PFAlgo-based "miniblock" from which candidates disjoint candidates were created
- `candidates: (ncand, nfeat_cand)`, all the produced PF candidates, [pdgid, pt, eta, phi]
- `candidate_block_id: (ncand)`, same unique ID for each candidate that was produced from each "miniblock"

`block_id` serves as the target for the supervised clustering. It is extracted by looking at disjoint subsets ("miniblocks") of all the elements based on the output of PFAlgo and PFCandidates. Most of these miniblocks have just 1-3 elements and produce 1-3 candidates.

**Comment by jmduarte** [comment]
@jpata great, thanks for the new input files!

I updated the [graph_data.py](test/graph_data.py) PyTorch geometric dataset class to use these.

Here's what one graph looks like now with all the elements, initially connecting all elements with dR < 0.2 (transparent blue), with true edges in red.

graph_eta_phi

We can iterate on the preprocessing cut. For now, I've put it to be dR < 0.4, but we discussed having a more sophisticated logic based on type and dR.

**Comment by lgray** [comment]
@jmduarte We should also consider starting from the connections determined by PFBlockAlgo as the preprocessing. 

It'll contain a bunch of detector specific considerations to begin with, particularly for HF where the associations are rather simple.

There are also issues for low pT tracks (in particular error scaling, and matching by outermost point) that we don't want to re-engineer.

**Comment by jpata** [comment]
I'm saving the PFAlgo distance matrix between elements: https://github.com/jpata/particleflow/blob/master/test/graph.py#L233

The data structure is as follows:
- `./data/TTbar/191009_155100/step3_AOD_1_ev0.npz`: elements, candidates, miniblock links as explained above
- `./data/TTbar/191009_155100/step3_AOD_1_dist0.npz`: sparse upper-triangular distance matrix [nelem, nelem]
- `./data/TTbar/191009_155100/step3_AOD_1_cl0.npz`: individual (miniblock, candidate) pairs for regression, see issue #4 

@jmduarte
I think all should now be in place to run the GNN clustering! I can give a try if the code is ready, or if needed I can check that the data structures work in the training code.

**Comment by jpata** [comment]
@jmduarte how do you feel about this - shall we merge and see how the graph clustering does for issue #6? I've prepared a singularity image, I was testing and I think all is working...

```
...
Stale epoch
batch loss = 0.14100: : 1it [00:00,  2.36it/s]
batch loss = 0.09143: : 1it [00:00, 58.26it/s]
scor 252037 stru 4792.0 stp 0 stn 252037 sfp 13 sfn 4792 stot 256842
Epoch: 13, Training Loss: 0.1410
               Validation Loss: 0.0914, Acc.: 0.5000, Eff.: 0.0000, FalsePos: 0.0001, FalseNeg: 1.0000, Purity: 0.0000
Stale epoch
Early stopping after 10 stale epochs
Final model saved to: /storage/user/jpata/particleflow/EdgeNet_13873_10e465f628_jpata.final.pth
batch loss = 0.06138: : 1it [00:00, 59.42it/s]
scor 249457 stru 4792.0 stp 166 stn 249291 sfp 2759 sfn 4626 stot 256842
Test Loss: 0.0614, Acc.: 0.5118, Eff.: 0.0346, FalsePos: 0.0109, FalseNeg: 0.9654, Purity: 0.0568
```

If we add `edge_attrs` based on the distance matrix in `step3_AOD_{0}_dist{1}.npz`, then I believe all the pieces are there to have an improved clustering in place.

**Comment by lgray** [comment]
How many events /epochs is that with? That's rather troubling performance if it's anything somewhat large.

**Comment by jpata** [comment]
This is just a few events and few epochs to check that it runs!

**Comment by lgray** [comment]
Ah, ok! I'd run it with a more realistically sized dataset and see if it gets good convergence before we merge, just to make sure there's not funny problem.

**Comment by jpata** [comment]
@jmduarte: if you have time to run a full training and check clustering performance, would be great!

**Comment by jmduarte** [comment]
Sure, I can give it a shot.

I believe we had discussed using a loose selection based on the distance matrix to create the initial graph. What do you think is a reasonable selection?

**Comment by jpata** [comment]
Great! I would just use any non-zero element in the distance matrix - I think this is what PFBlockAlgo is doing. Here a [link](https://github.com/jpata/particleflow/blob/master/test/train_clustering.py#L54) to how I accessed it for the baseline edge classifier (issue #6).

**Comment by jpata** [comment]
> Did the singularity `/storage/group/gpu/software/singularity/edge.simg` image work [1]? Otherwise, @vlimant can update the image.

I made a private singularity image with `torch_geometric` & friends here: `/storage/user/jpata/gpuservers/singularity/images/over_edge.simg`

**Comment by jmduarte** [comment]
- After updating the initial edges to those with some entry in the element distance matrix (blue), and the true/target edges to those elements with the same block id, an example graph looks like this:
graph_eta_phi Still quite crowded, but I think it makes sense. 
- I also added the distances as an "edge attribute", but we're not yet using this information in the training.
- After training the model on 7200 events (with 900 for validation) for a few epochs, the performance is reasonable:
```
Epoch: 24, Training Loss: 0.1492
               Validation Loss: 0.0888, Acc.: 0.8739, Eff.: 0.7891, FalsePos: 0.0414, FalseNeg: 0.2109, Purity: 0.7812
New best model saved to: /nfshome/jduarte/particleflow/EdgeNet_13873_10e465f628_jduarte.best.pth
```
- I think this is now merge-able and we can continue fine-tuning the model, etc.

**Comment by jpata** [comment]
Thanks Javier - great! I will merge this and we can continue fine-tuning. I think I should be able to integrate this GNN clustering directly to the end-to-end benchmark today (in PR #7).

**Pull request merged**
